const data = {
  products: [
    {
      id: "1",
      name: "Reinforced",
      category: "glass",
      price: 33.78,
      currency: "USD",
      image: {
        src: "https://www.builderspace.com/wp-content/uploads/2021/06/high-rise-glass-building.jpg",
        alt: "Reinforced glass",
      },
      bestseller: true,
      featured: false,
      details: null,
    },
    {
      id: "2",
      name: "Shape",
      category: "steel",
      price: 93.89,
      currency: "USD",
      image: {
        src: "https://www.montanstahl.com/wp-content/uploads/2017/06/Stainless-Steel-Structural-Section.jpg",
        alt: "Shape steel",
      },
      bestseller: false,
      featured: false,
      details: null,
    },
    {
      id: "3",
      name: "wave",
      category: "steel",
      price: 120.21,
      currency: "USD",
      image: {
        src: "https://thumbs.dreamstime.com/b/steel-wall-silver-wave-structure-background-texture-59701977.jpg",
        alt: "wave steel",
      },
      bestseller: false,
      featured: false,
      details: null,
    },
    {
      id: "4",
      name: "gold steel",
      category: "steel",
      price: 105,
      currency: "USD",
      image: {
        src: "https://marvel-b1-cdn.bc0a.com/f00000000211153/www.kloecknermetals.com/wp-content/uploads/2021/01/structural-steel-shapes.png",
        alt: "Shape steel",
      },
      bestseller: false,
      featured: false,
      details: null,
    },
    {
      id: "5",
      name: "Shape",
      category: "wood",
      price: 210,
      currency: "USD",
      image: {
        src: "https://img.freepik.com/free-photo/overhead-wooden-planks-background-with-copy-space_24972-537.jpg?w=2000",
        alt: "Shape wood",
      },
      bestseller: false,
      featured: false,
      details: null,
    },
    {
      id: "6",
      name: "pastel",
      category: "brick",
      price: 80,
      currency: "USD",
      image: {
        src: "https://images.unsplash.com/photo-1495578942200-c5f5d2137def?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max",
        alt: "pastel brick",
      },
      bestseller: true,
      featured: false,
      details: null,
    },
    {
      id: "7",
      name: "Shape",
      category: "concrete",
      price: 101,
      currency: "USD",
      image: {
        src: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/concrete-wall-royalty-free-image-1572896179.jpg",
        alt: "Shape steel",
      },
      bestseller: false,
      featured: false,
      details: null,
    },
    {
      id: "8",
      name: "Shape",
      category: "wood",
      price: 101,
      currency: "USD",
      image: {
        src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkLh-dINll0_NtaRvIoFPowA1LFT9Rdx5Bl-ku0XmyOLY66UNmTTW34_HKHFTIjdt16bA&usqp=CAU",
        alt: "Shape steel",
      },
      bestseller: false,
      featured: false,
      details: null,
    },
    {
      id: "9",
      name: "Shape",
      category: "steel",
      price: 101,
      currency: "USD",
      image: {
        src: "https://marvel-b1-cdn.bc0a.com/f00000000211153/www.kloecknermetals.com/wp-content/uploads/2021/01/structural-steel-shapes.png",
        alt: "Shape steel",
      },
      bestseller: false,
      featured: false,
      details: null,
    },
    {
      id: "10",
      name: "Shape",
      category: "brick",
      price: 101,
      currency: "USD",
      image: {
        src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSg6snV_Bz-QNjN931T_9shNWuJy3cLuySZoQ&usqp=CAU",
        alt: "Shape steel",
      },
      bestseller: false,
      featured: false,
      details: null,
    },
    {
      id: "11",
      name: "red brick",
      category: "brick",
      price: 101,
      currency: "USD",
      image: {
        src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBk5VsvsdYh6s6ZYrxsnSLSMy7jtabzYcp2Q&usqp=CAU",
        alt: "Shape steel",
      },
      bestseller: false,
      featured: false,
      details: null,
    },
    {
      id: "12",
      name: "Shape",
      category: "steel",
      price: 101,
      currency: "USD",
      image: {
        src: "https://marvel-b1-cdn.bc0a.com/f00000000211153/www.kloecknermetals.com/wp-content/uploads/2021/01/structural-steel-shapes.png",
        alt: "Shape steel",
      },
      bestseller: false,
      featured: false,
      details: null,
    },
    {
      id: "13",
      name: "surface",
      category: "copper",
      price: 500,
      currency: "USD",
      image: {
        src: "https://www.rmit.edu.au/content/dam/rmit/rmit-images/news/2021/dec/copper-antibacterial/GettyImages-869269460.jpg",
        alt: "Shape steel",
      },
      bestseller: false,
      featured: false,
      details: null,
    },
    {
      id: "14",
      name: "fiber",
      category: "carbon fiber",
      price: 60,
      currency: "USD",
      image: {
        src: "https://image.architonic.com/img_pro2-4/116/6568/carbon-fiber-anthracite-car-9001-b.jpg",
        alt: "Shape steel",
      },
      bestseller: false,
      featured: false,
      details: null,
    },
    {
      id: "15",
      name: "Shape",
      category: "steel",
      price: 101,
      currency: "USD",
      image: {
        src: "https://marvel-b1-cdn.bc0a.com/f00000000211153/www.kloecknermetals.com/wp-content/uploads/2021/01/structural-steel-shapes.png",
        alt: "Shape steel",
      },
      bestseller: false,
      featured: false,
      details: null,
    },
    {
      id: "16",
      name: "Shape",
      category: "steel",
      price: 101,
      currency: "USD",
      image: {
        src: "https://marvel-b1-cdn.bc0a.com/f00000000211153/www.kloecknermetals.com/wp-content/uploads/2021/01/structural-steel-shapes.png",
        alt: "Shape steel",
      },
      bestseller: false,
      featured: false,
      details: null,
    },
    {
      id: "17",
      name: "Shape",
      category: "steel",
      price: 101,
      currency: "USD",
      image: {
        src: "https://marvel-b1-cdn.bc0a.com/f00000000211153/www.kloecknermetals.com/wp-content/uploads/2021/01/structural-steel-shapes.png",
        alt: "Shape steel",
      },
      bestseller: false,
      featured: false,
      details: null,
    },
    {
      id: "18",
      name: "Shape",
      category: "steel",
      price: 101,
      currency: "USD",
      image: {
        src: "https://marvel-b1-cdn.bc0a.com/f00000000211153/www.kloecknermetals.com/wp-content/uploads/2021/01/structural-steel-shapes.png",
        alt: "Shape steel",
      },
      bestseller: false,
      featured: false,
      details: null,
    },
    {
      id: "19",
      name: "Shape",
      category: "steel",
      price: 101,
      currency: "USD",
      image: {
        src: "https://marvel-b1-cdn.bc0a.com/f00000000211153/www.kloecknermetals.com/wp-content/uploads/2021/01/structural-steel-shapes.png",
        alt: "Shape steel",
      },
      bestseller: false,
      featured: false,
      details: null,
    },
    {
      id: "20",
      name: "Shape",
      category: "steel",
      price: 101,
      currency: "USD",
      image: {
        src: "https://marvel-b1-cdn.bc0a.com/f00000000211153/www.kloecknermetals.com/wp-content/uploads/2021/01/structural-steel-shapes.png",
        alt: "Shape steel",
      },
      bestseller: false,
      featured: false,
      details: null,
    },
    {
      id: "21",
      name: "Shape",
      category: "steel",
      price: 101,
      currency: "USD",
      image: {
        src: "https://marvel-b1-cdn.bc0a.com/f00000000211153/www.kloecknermetals.com/wp-content/uploads/2021/01/structural-steel-shapes.png",
        alt: "Shape steel",
      },
      bestseller: false,
      featured: false,
      details: null,
    },
    {
      id: "22",
      name: "Shape",
      category: "steel",
      price: 101,
      currency: "USD",
      image: {
        src: "https://marvel-b1-cdn.bc0a.com/f00000000211153/www.kloecknermetals.com/wp-content/uploads/2021/01/structural-steel-shapes.png",
        alt: "Shape steel",
      },
      bestseller: false,
      featured: false,
      details: null,
    },
    {
      id: "23",
      name: "Shape",
      category: "steel",
      price: 101,
      currency: "USD",
      image: {
        src: "https://marvel-b1-cdn.bc0a.com/f00000000211153/www.kloecknermetals.com/wp-content/uploads/2021/01/structural-steel-shapes.png",
        alt: "Shape steel",
      },
      bestseller: false,
      featured: false,
      details: null,
    },
    {
      id: "24",
      name: "Shape",
      category: "steel",
      price: 101,
      currency: "USD",
      image: {
        src: "https://marvel-b1-cdn.bc0a.com/f00000000211153/www.kloecknermetals.com/wp-content/uploads/2021/01/structural-steel-shapes.png",
        alt: "Shape steel",
      },
      bestseller: false,
      featured: false,
      details: null,
    },
    {
      id: "25",
      name: "Recycled Plastic",
      category: "plastic",
      price: 105,
      currency: "USD",
      image: {
        src: "https://previews.123rf.com/images/tinnko/tinnko1203/tinnko120300032/12886631-plastic-building-blocks-background-colorful-children-s-toys.jpg",
        alt: "Recycled Plastic",
      },
      bestseller: false,
      featured: true,
      details: {
        weight: 2340,
        thickness: 2,
        description: "",
        recommendations: [
          {
            src: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/concrete-wall-royalty-free-image-1572896179.jpg",
            alt: "wood",
          },
          {
            src: "http://inhabitat.com/wp-content/blogs.dir/1/files/2018/02/wood-600x480.jpg",
            alt: "wood",
          },
          {
            src: "https://images.unsplash.com/photo-1495578942200-c5f5d2137def?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max",
            alt: "brick",
          },
        ],
      },
    },
  ],
};
export default data;
